[project]
name = "mcptooldefinitions"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "anthropic>=0.72.0",
    "arxiv>=2.3.0",
    "mcp>=1.20.0",
    "nest-asyncio>=1.6.0",
    "python-dotenv>=1.2.1",
]
