[project]
name = "mcptooldefinitions"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "arxiv>=2.3.0",
    "mcp>=1.20.0",
]
